README.md, tutorials/1-quickstart.ipynb
Two changes to the docs:
1. The docs say that a `Job` requires the returns to be serializable to JSON. It's also true that the inputs must be serializable, which I think is important to note. It wasn't intuitive to me at least.
2. I fixed a broken URL.
```python
~\Anaconda3\envs\cms2\lib\site-packages\jobflow\core\job.py in get_job(*args, **kwargs)
200                         args = args[1:]
201
--> 202             return Job(
203                 function=f,
204                 function_args=args,
~\Anaconda3\envs\cms2\lib\site-packages\jobflow\core\job.py in __init__(self, function, function_args, function_kwargs, output_schema, uuid, index, name, metadata, config, host, **kwargs)
353         # this is a possible situation but likely a mistake
354         all_args = …
```
=> Clarify docs

src/jobflow/core/job.py, tests/core/test_job.py
Addresses #120. 
Currently, it is not possible to modify the `manager_config` of any jobs produced from a detour, addition, or replacement. The only option is the default (`pass_manager_config=True`), which passes the parent job's config to the child or `pass_manager_config=False` which passes a clean slate. Ideally, there should be a way for the user to pass a dictionary that won't be used in the parent job but will be used for any downstream jobs.
That is what this PR does. It adds a new kwarg `response_manager_config` to `JobConfig` for precisely this purpose.
Example:
```python
job.config.response_manager_config["_fworker"] = "my_response_fworker"
```
=> Pass an alternate manager_config to child jobs made via a detour, addition, or replacement

src/jobflow/core/reference.py, tests/core/test_reference.py
Implement a first level of validation of outputs with nested Schemas.
The current implementation ignores the checks if nested schemas are inside `Union`, `List`, `Dict`, while it correctly validates if inside `Optional`. 
As previously discussed (#116), implementing the checks for `Union` will probably be challenging and it will not be supported for the time being. Should we do the same for `List` and `Dict`?
=> Validate subschema

src/jobflow/settings.py
Explicitly replace the `~` for the `DEFAULT_CONFIG_FILE_PATH`.
I actually have to amend what I said yesterday(#116): it seems that I still have the same issue. In particular, looking at the code, it seems that the `DEFAULT_CONFIG_FILE_PATH` is used here:
https://github.com/materialsproject/jobflow/blob/fbd5868394c6f4f6b4f2e0ccf4b7ff7d21fe7258/src/jobflow/settings.py#L92
and it does not look like the expanduser gets applied to this anywhere before being accessed. Am I missing something?
=> fix home path

tests/core/test_flow.py
It bothered me that the `DivMaker` in the unit test was an addition operator instead of a division operator. Now updated. Functionally, this does absolutely nothing to the existing unit tests, but... *shrugs*
=> Update divmaker test

src/jobflow/core/store.py, src/jobflow/settings.py, tests/test_settings.py
Now checks the `dict_spec` for the word "type" and recursively calls the constructor.
=> add s3store yaml parsing

src/jobflow/core/flow.py, src/jobflow/core/job.py, tests/core/test_flow.py, tests/core/test_job.py, tutorials/1-quickstart.ipynb
Allowing the storage of the list of uuids of the Flows containing a job. The idea is to be able to group jobs belonging to the same Flow when querying the Job store.
The list of hosts is supposed to be ordered in such a way that the first element is the first Flow containing the Job/Flow, with subsequent elements identifying the increasing containers.
The list is stored in the `hosts` attribute. `host` is removed and replaced by a property giving the first element of `hosts`, if present. 
An additional issue that emerged was that, when using Fireworks as a manager, for restart, detours and additions the new Jobs are always wrapped inside a Flow, leading to clashes with the list of `hosts`. The easiest way that I have found to fix this was to always wrap restart/detour/addition Jobs into a …
=> List of hosts in Jobs and Flows

examples/restarts.py, src/jobflow/core/flow.py, src/jobflow/core/job.py, src/jobflow/core/reference.py, src/jobflow/core/store.py, src/jobflow/managers/local.py, src/jobflow/settings.py
* Fix `restart.py` example, restart->replace
* A few typo fixes
=> Typo fixes

src/jobflow/core/flow.py, src/jobflow/core/job.py, tests/core/test_flow.py, tests/test_settings.py
Add functionalities to modify the list of Jobs/Flows in a Flow and prevent direct changes to it.  
`jobs` in `Flow` is a private tuple and should only be modified by the `add_jobs`, `remove_jobs` methods. Also `output` undergoes checks if it gets modified outside the `__init__` to avoid missing references.
I also changed one test of the settings since it was always picking my ~/.jobflows.yaml file and always failing locally.
=> Control changes to job list in Flow

docs/src/changelog.rst, src/jobflow/core/flow.py, src/jobflow/core/job.py, src/jobflow/core/maker.py, src/jobflow/core/reference.py, src/jobflow/managers/local.py, src/jobflow/settings.py, tests/core/test_flow.py, tests/core/test_job.py, tests/core/test_reference.py
New features:
- Added an `update_metadata` function for updating the metadata of jobs and flows (Fixes #115).
- Added an `update_config` function for updating the config (included manager_config) of jobs and flows (Addresses #73).
- Added the `DIRECTORY_FORMAT` option in settings for controlling the date time format used to create new directories (Fixes #128).
Bug fixes:
- OutputReferences are no longer iterable (Fixes #105).
- Docstring clarifications (Fixes #114).
=> Add job and flow update functions

setup.py, src/jobflow/core/store.py, tests/core/test_store.py
Currently, the "job_uuid" is not stored in the index store of the S3Store.
Which means they are not searchable even though they are in the query results.
This should fix that behavior.
=> searchable fields

src/jobflow/core/job.py, src/jobflow/core/maker.py
This makes checking and validating maker parameters for complex makers much easier by recycling (with some modification) the code used for update_kwargs.
- Created a general function that can update or validate makers.
- The `recursive_call` function does not actually need to be recursive since the location found by `find_key` already contains all the objects that need to be worked on.
- We just have to reverse sort them by length to make sure we work on the deepest objects first.
- Then we can call a general function on all the Makers in the filter and update them if desired.
- The fact that `location` is sorted will make sure the updates are properly propagated up the chain.
The original PR message was for a smaller fix.
> ## Prevent extras calls to update_kwargs
> 
> I think if …
=> update_kwargs patch

src/jobflow/core/store.py, src/jobflow/settings.py, tests/test_settings.py
One of the main advantages of jobflow is to be able to start running a workflow (Flow) almost without any configuration, at least in terms of databases to set up (well you still have to configure e.g. vasp, pseudos, ... for atomate2). In atomate2, additional stores are used in the JobStore (e.g. "data"). The default JOB_STORE used a MemoryStore for the "main" store (the JobStore.docs_store) but did not set any default for the additional stores. These additional stores of course are not known in advance (their keys in the dict). For atomate2, it uses "data" but other implementations may use other key(s) for these additional stores. This PR solves this by using a defaultdict with a factory function (lambda) that returns a MemoryStore the first time it is accessed.
Include a summary of major …
=> Added default for additional_stores in the settings.

src/jobflow/core/flow.py, src/jobflow/core/job.py, tests/core/test_job.py
Implementing delayed updates for config and metadata as discussed in #193 
Added job name in the stored job document.
Fixing few issues in the update_config/metadata:
- The `function_filter` was working only in the case of instantiated `Job`s and not for `@job` decorated functions. Switched to checking the wrapped functions. 
- The logic for `name_filter` was wrong in case of the job name is `None`. In principle the name is never `None`, but fixed it anyway
=> Delayed updates to config and metadata

src/jobflow/core/job.py
A small change to allow `Response.output` to be type hinted.
This should allow method signatures like:
`my_job() -> Response[int]`
or 
`my_job() -> Response[Structure]`
to work and be type checked correctly by `mypy` or similar, while `my_job() -> Response` should still work as previously. The type in the square brackets is the type for the `Response.output` specifically.
Not sure if there's an easier way to do this, but could be helpful?
=> Allow `Response.output` to be type hinted

src/jobflow/core/store.py, src/jobflow/utils/find.py, tests/core/test_store.py
This should fix the following bug:
https://github.com/materialsproject/atomate2/issues/291
Currently, there is a problem when you serialize nested data when you have `Child` nested in `Parent`, both will get uploaded to the `additional_store`.  But I think you should ever only serialize the `Parent` in all but a few exceptional cases.
=> [Bug Fix] Fixed nested data storage bug

docs/tutorials/1-quickstart.ipynb, src/jobflow/utils/graph.py, tests/utils/test_graph.py
Addresses #301 
Based on @mkhorton's suggestion and code snippet, I've added a function to enable visualising Flow's in mermaid.
I made a few adjustments to allow for:
- Nested flows and flow boxes
- Supporting flows with no connections between jobs.
These may be of interest to @JaGeo. Note, the flow boxes are disabled by default but I've included them in these plots.
=> Add `to_mermaid` function to covert flow to mermaid syntax

src/jobflow/core/store.py, tests/core/test_store.py
Fixed JobStore.from_dict_spec so that the original dict_spec is not modified.
The spec is now copied so that if this is used programmatically, the type is not removed from the original spec_dict, which may be used afterwards, (e.g. stored in a database), or if there is some validation by a pydantic schema.
@utf For information, this is making the jobflow-remote fail in some of the config cases.
Include a summary of major changes in bullet points:
- Modification of the internal `_construct_store` method so that the original dict_spec is not modified.
None
None
=> Fixed JobStore.from_dict_spec so that the original dict_spec is not modified

src/jobflow/utils/graph.py
Closes the issue described in #349 . As described there, I am not sure if I missed a use-case for the following line https://github.com/materialsproject/jobflow/blob/09ffa16026b5682f7947045fedf6376ce7276d7f/src/jobflow/utils/graph.py#L246
I did not see any change in other tested workflow visualizations.
=> fix mermaid with one job (in a flow)

src/jobflow/utils/graph.py
Another tiny fix to the graphs utils.
=> Add to_mermaid zu all in graph utils

src/jobflow/managers/fireworks.py, tests/managers/test_fireworks.py
Picking up #320.
I think the changed originally proposed would add alot of redundant information into the document/db.
=> Propagate tags from fw_spec to metadata

src/jobflow/utils/find.py, tests/utils/test_find.py
Adds the `allow_bson=True` kwarg to the `jsanitize` invocation in `contains_job_or_flow` utility function, and a corresponding test case. I recently tried to pass an object containing a `datetime.datetime` in it as an input to a job (specifically, the object was an emmet `TaskDoc`. This object was the output of another job (and I had retrieved it from the jobstore).
I noticed that every other invocation of jsanitize in the codebase uses `allow_bson=True`, with the exception of the one in `Job::as_dict`, so I concluded that this might be a bug. Please feel free to close if this behavior is intentional! However, I think it's useful to allow things like `datetime`s as inputs (at least to allow the use of TaskDocs as input parameters).
Work-in-progress pull requests are encouraged, but please …
=> Allow bson objects as job inputs, e.g. datetime.datetimes

src/jobflow/core/job.py, tests/core/test_job.py
An extension of https://github.com/materialsproject/jobflow/pull/375. If we allow bson inputs to be serialized, then job serialization must also accommodate that (since job serialization involves serializing the function_args, i.e. inputs).
Work-in-progress pull requests are encouraged, but please put [WIP] in the pull request
title.
Before a pull request can be merged, the following items must be checked:
The easiest way to handle this is to run the following in the **correct sequence** on
your local machine. Start with running [black](
https://black.readthedocs.io/en/stable/index.html) on your new code. This will
automatically reformat your code to PEP8 conventions and removes most issues. Then run
[pycodestyle](https://pycodestyle.readthedocs.io/en/latest/), followed by [flake8]( …
=> Also allow_bson in job serialization

.pre-commit-config.yaml, docs/tutorials/8-fireworks.md, pyproject.toml, src/jobflow/core/flow.py, src/jobflow/core/job.py, src/jobflow/core/reference.py, tests/core/test_flow.py, tests/core/test_job.py, tests/managers/test_local.py
Closes #368.
```py
from pymatgen.core import Lattice, Structure
from atomate2.vasp.flows.mp import MPMetaGGARelax
struct = Structure(
lattice=Lattice.cubic(3),
species=("Fe", "Fe"),
coords=((0, 0, 0), (0.5, 0.5, 0.5)),
)
flow = MPMetaGGARelax().make(structure)
len(flow)
>>> 3
print(flow)
>>> Flow(name='MP Meta-GGA Relax', uuid='d43cd776-fb64-40f0-bacf-1933ee2342b8')
consisting of 3 jobs:
1. Job(name='MP pre-relax', uuid='99a016af-eb9d-4d7a-8454-85ecf6b59d41')
2. Job(name='MP meta-GGA Relax', uuid='496006d6-5375-49ce-91a8-cf53483173e1')
3. Job(name='MP meta-GGA Static', uuid='8fe17841-a536-4d39-9bfa-dd83bc7900a2')
```
=> `Flow` + `Job` magic methods

src/jobflow/managers/fireworks.py, tests/managers/test_fireworks.py
Closes #395.
62eb2c9 fix `TypeError` when passing name to `flow_to_workflow()`
bb3d972 test `flow_to_workflow()` with custom name
=> Fix `TypeError` when passing name to `flow_to_workflow()`

src/jobflow/core/flow.py, src/jobflow/managers/fireworks.py, src/jobflow/managers/local.py, tests/core/test_flow.py, tests/managers/test_fireworks.py, tests/managers/test_local.py
Currently Jobflow prevents using an `OutputReference` as an input for a Job/Flow if the Job being referred does not belong to the same Flow.
However, I think there are cases where it could be useful to pass the reference to the output of a Job/Flow that has finished previously. 
Of course the use of the external reference could be avoided by fetching the output of the first Flow and pass it as an input of the new Flow. But what if the output is very large and does not fit in the MongoDB size limit? Allowing external references will allow to avoid this kind of issues, avoid repetition of the data in the DB and potentially allow to reconstruct connections between different flows.
I thought it would have been easier to test this option and directly open a PR rather than discussing it in an …
=> External references

docs/tutorials.rst, docs/tutorials/2-introduction.ipynb
Closes #410.
This PR adds a hyperlink to @jageo's very nice Jobflow tutorials and fixes a broken hyperlink. I also removed a notice that more tutorials will be added "soon" so as not give a false impression. Besides, we covered most of the main content now.
=> Link to @jageo's tutorials and fix a broken link

.github/workflows/testing.yml, pyproject.toml
- I added Python 3.11 to the test suite and updated the relevant parts of the repo to make it clear 3.11 is supported.
- I pinned pydantic to <2 for now.
- I updated the classifier for the project status to "Development Status :: 5 - Production/Stable"
=> Add tests for Python 3.11

pyproject.toml, src/jobflow/settings.py, tests/test_settings.py
Addresses #411, and adds moto as a testing dependency.
- moto is added as a test dependency, but this is because it is already used in a test in tests/core/test_store.py
Work-in-progress pull requests are encouraged, but please put [WIP] in the pull request
title.
Before a pull request can be merged, the following items must be checked:
The easiest way to handle this is to run the following in the **correct sequence** on
your local machine. Start with running [black](
https://black.readthedocs.io/en/stable/index.html) on your new code. This will
automatically reformat your code to PEP8 conventions and removes most issues. Then run
[pycodestyle](https://pycodestyle.readthedocs.io/en/latest/), followed by [flake8](
http://flake8.pycqa.org/en/latest/).
Note that the CI system will run all …
=> Add warning when jobflow.yaml is blank or badly formatted

pyproject.toml, src/jobflow/core/reference.py, src/jobflow/settings.py, tests/core/test_reference.py
@utf: As you likely saw, Pydantic 2 introduced many new features and changes. In an effort to support Pydantic 2, much of the MP software stack has now been modified accordingly. With maggma, emmet, and monty now supporting Pydantic 2, I have updated Jobflow to match.
Tagging @munrojm who initiated this switch for the rest of the MP stack. I haven't gotten all the tests to pass yet --- suggestions are very welcome!
Closes #422.
=> Add support for Pydantic 2

src/jobflow/core/flow.py, src/jobflow/core/job.py, src/jobflow/core/maker.py, src/jobflow/core/reference.py, src/jobflow/core/state.py, src/jobflow/core/store.py, src/jobflow/managers/fireworks.py, src/jobflow/managers/local.py, src/jobflow/settings.py, src/jobflow/utils/dict_mods.py, src/jobflow/utils/enum.py, src/jobflow/utils/find.py, src/jobflow/utils/graph.py, src/jobflow/utils/log.py, tests/core/test_store.py
Related PR https://github.com/materialsproject/atomate2/pull/540 and issue https://github.com/materialsproject/atomate2/issues/539.
=> Remove `__all__` from all modules

.github/workflows/testing.yml, .pre-commit-config.yaml, paper/paper.md
The code-blocks have two line breaks in many places, in accordance with `black`. However, the generous line-spacing is somewhat bothersome in a journal article format. I had intended there to be only one line break, but I think Alex's text editor may have auto-reformatted it upon upload. This PR reverts back to the single line-break format I had intended.
Partially addresses (but does not close) #453.
@janosh: Could you please merge this too? Thanks!
Edit: How can we have the lint test skip the `paper.md` file altogether?
=> JOSS Paper: Reduce line-spacing in code blocks

paper/refs.bib
The reference for Prefect was missing its year.
=> JOSS Paper update: Add missing year to `refs.bib`

.github/workflows/testing.yml, .pre-commit-config.yaml, README.md, docs/conf.py, examples/replace.py, pyproject.toml, src/jobflow/core/flow.py, src/jobflow/core/job.py, src/jobflow/core/reference.py, src/jobflow/core/store.py, src/jobflow/managers/fireworks.py, src/jobflow/schemas/job_output_schema.py, src/jobflow/utils/find.py, tests/core/test_reference.py, tests/test_settings.py
We could hold off on this. Only reason for doing this is to stay in sync with `numpy` and the rest of the MP ecosystem (e.g. https://github.com/materialsproject/pymatgen/pull/3283).
=> Bump minimum Python version to 3.9

.pre-commit-config.yaml, pyproject.toml, src/jobflow/_version.py, tests/test_version.py
From [https://setuptools.pypa.io](https://setuptools.pypa.io/en/latest/pkg_resources.html):
> Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.
=> Replace deprecated `pkg_resources` with `importlib.metadata.version`

.pre-commit-config.yaml, examples/data_store.py, pyproject.toml, src/jobflow/core/flow.py, src/jobflow/core/reference.py, src/jobflow/core/state.py, src/jobflow/core/store.py, src/jobflow/managers/fireworks.py, src/jobflow/managers/local.py, src/jobflow/utils/enum.py, src/jobflow/utils/find.py, src/jobflow/utils/graph.py, tests/conftest.py, tests/core/test_flow.py, tests/core/test_job.py, tests/core/test_job_output_schema.py, tests/core/test_maker.py, tests/core/test_reference.py, tests/core/test_store.py, tests/managers/test_fireworks.py, tests/managers/test_local.py, tests/test_version.py, tests/utils/test_dict_mods.py, tests/utils/test_find.py, tests/utils/test_graph.py
I don't think we should ignore `PT011: pytest-raises-too-broad` long-term. Better to add `match="expected error message"` to all `pytest.raises()`. But there were 45 violations so I didn't fix all of them.
=> Match `atomate2` `ruff` config

src/jobflow/core/flow.py, src/jobflow/utils/graph.py, tests/core/test_flow.py, tests/core/test_job.py, tests/core/test_maker.py, tests/managers/conftest.py, tests/managers/test_fireworks.py, tests/managers/test_local.py
Saves accessing `flow.jobs` a bunch.
=> Simplify code by using `Flow` methods `__len__` and `__getitem__`

paper/refs.bib
Addresses https://github.com/openjournals/joss-reviews/issues/5995#issuecomment-1808396589.
Namely, I previously used a minimal format for the Zenodo references. Now, I have used the one auto-generated by Zenodo. One downside of this approach is that the author list includes all contributors to the repo, no matter how large or small their contributions are.
I see two ways to go about this:
1) Just accept it and move on.
2) Keep the rest of the metadata but remove the `author` field.
@utf, any thoughts?
=> JOSS: Add more complete Zenodo reference info

src/jobflow/core/reference.py, src/jobflow/managers/local.py, tests/managers/test_local.py
So users don't have to change directory to control where flows run.
Added a test and docs.
=> `run_locally()` add `root_dir: str | Path | None` keyword

src/jobflow/core/flow.py, tests/core/test_flow.py
There was an issue with the (de)serialization of a Flow. Since the hosts are added when a Flow is created from a list of Flows/Jobs, during deserialization hosts were duplicated for each of the jobs contained in the Flow.
This PR should fix this.
=> fix Flow deserialization for hosts

docs/index.rst, docs/stores.md
This PR addresses a comment raised in https://github.com/openjournals/joss-reviews/issues/5995. We now include documentation for how to modify the Jobflow settings to use a custom data store. This was already described in the API documentation, but now a concrete example is provided in the main documentation.
One open question: There is basically the [same info](https://materialsproject.github.io/atomate2/user/install.html#jobflow-yaml) in a portion of the Atomate2 documentation. Do we instead just link to it to prevent duplication of content? Or is there value in having a dedicated page with Jobflow. I can see arguments for both. In any case, this PR provides an example.
=> Add documentation for how to deal with stores beyond `MemoryStore`

docs/tutorials.rst
Closes #501.
Couldn't find any other broken rst/md links.
=> Fix tutorial link formatting in docs

src/jobflow/core/job.py, tests/core/test_job.py
I was trying to use a function from the standard library to create a simple example and I got an error:
```python
import time
from jobflow import Job, SETTINGS
j = Job(time.sleep, (1,))
j.run(SETTINGS.JOB_STORE)
```
gives
> TypeError: time.sleep() takes exactly one argument (2 given)
The reason is that `sleep` has a `__self__` attribute and in `Job` it is then converted to a bound method. This seems to be shared by most (all?) the functions in the standard library. 
To adress this I changed the check performed in `Job.run()` assuming that if the `__self__` is a module, than the callable should not be converted to a method. I am not entirely sure if I may be missing some case where this is not true.
=> Fix handling of function from standard library

src/jobflow/managers/local.py, src/jobflow/settings.py, tests/managers/test_local.py
Currently, whenever any `run_locally` call fails.
The stack trace is produced at the end and we only have access to the error via a logger even
if you set `RAISE_IMMEDIATELY: true`, the stack trace will be provided where the excution actually failed.
This allows you to move around better within a debugger.
=> Optional Flag to help Debugging

src/jobflow/core/store.py
Fixes a minor typo I stumbled upon in #542.
=> Fix `JobStore.from_file` docstring

src/jobflow/managers/fireworks.py, tests/managers/conftest.py, tests/managers/test_fireworks.py
I have seen that in some cases the `JobFiretask` does not properly serialize a Job.
Consider the case of a Maker with a Callable as an attribute.
```python
from fireworks import LaunchPad
from jobflow.managers.fireworks import job_to_firework
from dataclasses import dataclass
from typing import Callable
from jobflow import Maker, job
def print_function():
print("TEST")
@dataclass
class CallableMaker(Maker):
f: Callable
name: str = "CallableMaker"
@job
def make(self, *args, **kwargs):
self.f()
j = CallableMaker(f=print_function).make()
fw = job_to_firework(j)
lpad = LaunchPad.auto_load()
lpad.add_wf(fw)
```
When running this, in the firework DB you have
```json
{
"spec": {
"_tasks": [
{
"job": {
"@module": "jobflow.core.job",
"@class": "Job",
"@version": "0.1.14.post122+g6439853", …
```
=> jsanitize fireworks Task

.github/workflows/testing.yml
`uv` continues to impress. 😄 
CI install time went from ~30s to 6s
=> Migrate from `pip` to `uv` for CI dependency install

src/jobflow/core/job.py
This is a follow-up of #578 . As it turns out, `pycharm` only reacts on the `@overload` if the original function is also annotated. This is also in agreement with `mypy`.
=> fix @job annotation (again)

src/jobflow/core/flow.py, src/jobflow/core/job.py
Hi @utf , @davidwaroquiers ,
I have made a draft implementation to address #639 . Let me know what you think. I hope I haven't overlooked anything.
=> Add dynamic option to append_name

src/jobflow/core/job.py
The examples in the docstring of the Job class used args instead of function_args as an argument. These are fixed in this very small PR.
=> Fix docstring in Job.

src/jobflow/core/flow.py, src/jobflow/core/job.py, src/jobflow/managers/local.py, tests/core/test_flow.py, tests/core/test_job.py
`Flow.update_metadata` is now much more similar to and has reached feature parity with `Job.update_metadata`:
https://github.com/materialsproject/jobflow/blob/367836b0d51a89fa58a9d685c4cdb9fc7f806c01/src/jobflow/core/job.py#L922-L930
=> Add `Flow.metadata` attribute and `Flow.update_metadata` method

src/jobflow/core/flow.py, src/jobflow/core/job.py, src/jobflow/utils/uuid.py
Changing the default value of `callback_filter` in the `update_metadata` function of both `Job` and `Flow` from a lambda to `None`. Having its default value be a lamdba function means that it cannot be round-trip de-/serialized:
```
from monty.json import MontyEncoder, MontyDecoder
f = lambda _ : True
encoded = MontyEncoder().encode(f)
print(encoded)
>>> '{"@module": "__main__", "@callable": "<lambda>", "@bound": null}'
decoded = MontyDecoder().decode(encoded)
print(decoded)
>>> {'@module': '__main__', '@callable': '<lambda>', '@bound': None}
```
This causes issues in fireworks with the newest release of jobflow. Linking relevant discussion [here](https://github.com/materialsproject/jobflow/pull/679#discussion_r1866290870) and tagging @janosh  and @utf for thoughts
Because lambda's aren't …
=> Change default callback_filter in update_metadata
